"""Centralized theme constants for the SNBR TMS App GUI."""

# Fonts
FONT_FAMILY = "Segoe UI"
FONT_TITLE = (FONT_FAMILY, 22, "bold")
FONT_HEADING = (FONT_FAMILY, 14, "bold")
FONT_BODY = (FONT_FAMILY, 13)
FONT_SMALL = (FONT_FAMILY, 11)
FONT_SUBTITLE = (FONT_FAMILY, 13)
FONT_BUTTON = (FONT_FAMILY, 13, "bold")

# Accent colors
ACCENT_COLOR = "#1F6AA5"
ACCENT_HOVER = "#174F7A"
ERROR_COLOR = "#E74C3C"
SUCCESS_COLOR = "#2ECC71"
DISABLED_FG = "#6B7280"
SUBTITLE_COLOR = ("#4B5563", "#B0B8C4")

# Padding / spacing
PAD_X = 30
PAD_Y = 12
SECTION_PAD_Y = 20
ENTRY_HEIGHT = 38
BUTTON_HEIGHT = 36
CORNER_RADIUS = 8
